//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientData
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientLastName { get; set; }
        public string ClientCell { get; set; }
        public Nullable<decimal> ClientPayment { get; set; }
        public Nullable<bool> HasClubCard { get; set; }
        public string ClientPassword { get; set; }
    
        public virtual User User { get; set; }
    }
}
