//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Clients { get; set; }
        public int Sellers { get; set; }
        public int Managers { get; set; }
        public int d { get; set; }
    
        public virtual ManagerData ManagerData { get; set; }
        public virtual SellersData SellersData { get; set; }
        public virtual ClientData ClientData { get; set; }
        public virtual da da { get; set; }
    }
}
